export interface Country {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
}

const getFlagEmoji = (countryCode: string) => {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
};

export const countries: Country[] = [
  { name: "Afghanistan", code: "af", dialCode: "+93", flag: getFlagEmoji("af") },
  { name: "Albania", code: "al", dialCode: "+355", flag: getFlagEmoji("al") },
  { name: "Algeria", code: "dz", dialCode: "+213", flag: getFlagEmoji("dz") },
  { name: "American Samoa", code: "as", dialCode: "+1684", flag: getFlagEmoji("as") },
  { name: "Andorra", code: "ad", dialCode: "+376", flag: getFlagEmoji("ad") },
  { name: "Angola", code: "ao", dialCode: "+244", flag: getFlagEmoji("ao") },
  { name: "Anguilla", code: "ai", dialCode: "+1264", flag: getFlagEmoji("ai") },
  { name: "Antigua and Barbuda", code: "ag", dialCode: "+1268", flag: getFlagEmoji("ag") },
  { name: "Argentina", code: "ar", dialCode: "+54", flag: getFlagEmoji("ar") },
  { name: "Armenia", code: "am", dialCode: "+374", flag: getFlagEmoji("am") },
  { name: "Aruba", code: "aw", dialCode: "+297", flag: getFlagEmoji("aw") },
  { name: "Australia", code: "au", dialCode: "+61", flag: getFlagEmoji("au") },
  { name: "Austria", code: "at", dialCode: "+43", flag: getFlagEmoji("at") },
  { name: "Azerbaijan", code: "az", dialCode: "+994", flag: getFlagEmoji("az") },
  { name: "Bahamas", code: "bs", dialCode: "+1242", flag: getFlagEmoji("bs") },
  { name: "Bahrain", code: "bh", dialCode: "+973", flag: getFlagEmoji("bh") },
  { name: "Bangladesh", code: "bd", dialCode: "+880", flag: getFlagEmoji("bd") },
  { name: "Barbados", code: "bb", dialCode: "+1246", flag: getFlagEmoji("bb") },
  { name: "Belarus", code: "by", dialCode: "+375", flag: getFlagEmoji("by") },
  { name: "Belgium", code: "be", dialCode: "+32", flag: getFlagEmoji("be") },
  { name: "Belize", code: "bz", dialCode: "+501", flag: getFlagEmoji("bz") },
  { name: "Benin", code: "bj", dialCode: "+229", flag: getFlagEmoji("bj") },
  { name: "Bermuda", code: "bm", dialCode: "+1441", flag: getFlagEmoji("bm") },
  { name: "Bhutan", code: "bt", dialCode: "+975", flag: getFlagEmoji("bt") },
  { name: "Bolivia", code: "bo", dialCode: "+591", flag: getFlagEmoji("bo") },
  { name: "Bosnia and Herzegovina", code: "ba", dialCode: "+387", flag: getFlagEmoji("ba") },
  { name: "Botswana", code: "bw", dialCode: "+267", flag: getFlagEmoji("bw") },
  { name: "Brazil", code: "br", dialCode: "+55", flag: getFlagEmoji("br") },
  { name: "British Virgin Islands", code: "vg", dialCode: "+1284", flag: getFlagEmoji("vg") },
  { name: "Brunei", code: "bn", dialCode: "+673", flag: getFlagEmoji("bn") },
  { name: "Bulgaria", code: "bg", dialCode: "+359", flag: getFlagEmoji("bg") },
  { name: "Burkina Faso", code: "bf", dialCode: "+226", flag: getFlagEmoji("bf") },
  { name: "Burundi", code: "bi", dialCode: "+257", flag: getFlagEmoji("bi") },
  { name: "Cambodia", code: "kh", dialCode: "+855", flag: getFlagEmoji("kh") },
  { name: "Cameroon", code: "cm", dialCode: "+237", flag: getFlagEmoji("cm") },
  { name: "Canada", code: "ca", dialCode: "+1", flag: getFlagEmoji("ca") },
  { name: "Cape Verde", code: "cv", dialCode: "+238", flag: getFlagEmoji("cv") },
  { name: "Cayman Islands", code: "ky", dialCode: "+1345", flag: getFlagEmoji("ky") },
  { name: "Central African Republic", code: "cf", dialCode: "+236", flag: getFlagEmoji("cf") },
  { name: "Chad", code: "td", dialCode: "+235", flag: getFlagEmoji("td") },
  { name: "Chile", code: "cl", dialCode: "+56", flag: getFlagEmoji("cl") },
  { name: "China", code: "cn", dialCode: "+86", flag: getFlagEmoji("cn") },
  { name: "Colombia", code: "co", dialCode: "+57", flag: getFlagEmoji("co") },
  { name: "Comoros", code: "km", dialCode: "+269", flag: getFlagEmoji("km") },
  { name: "Cook Islands", code: "ck", dialCode: "+682", flag: getFlagEmoji("ck") },
  { name: "Costa Rica", code: "cr", dialCode: "+506", flag: getFlagEmoji("cr") },
  { name: "Croatia", code: "hr", dialCode: "+385", flag: getFlagEmoji("hr") },
  { name: "Cuba", code: "cu", dialCode: "+53", flag: getFlagEmoji("cu") },
  { name: "Curacao", code: "cw", dialCode: "+599", flag: getFlagEmoji("cw") },
  { name: "Cyprus", code: "cy", dialCode: "+357", flag: getFlagEmoji("cy") },
  { name: "Czech Republic", code: "cz", dialCode: "+420", flag: getFlagEmoji("cz") },
  { name: "Democratic Republic of the Congo", code: "cd", dialCode: "+243", flag: getFlagEmoji("cd") },
  { name: "Denmark", code: "dk", dialCode: "+45", flag: getFlagEmoji("dk") },
  { name: "Djibouti", code: "dj", dialCode: "+253", flag: getFlagEmoji("dj") },
  { name: "Dominica", code: "dm", dialCode: "+1767", flag: getFlagEmoji("dm") },
  { name: "Dominican Republic", code: "do", dialCode: "+1809", flag: getFlagEmoji("do") },
  { name: "East Timor", code: "tl", dialCode: "+670", flag: getFlagEmoji("tl") },
  { name: "Ecuador", code: "ec", dialCode: "+593", flag: getFlagEmoji("ec") },
  { name: "Egypt", code: "eg", dialCode: "+20", flag: getFlagEmoji("eg") },
  { name: "El Salvador", code: "sv", dialCode: "+503", flag: getFlagEmoji("sv") },
  { name: "Equatorial Guinea", code: "gq", dialCode: "+240", flag: getFlagEmoji("gq") },
  { name: "Eritrea", code: "er", dialCode: "+291", flag: getFlagEmoji("er") },
  { name: "Estonia", code: "ee", dialCode: "+372", flag: getFlagEmoji("ee") },
  { name: "Ethiopia", code: "et", dialCode: "+251", flag: getFlagEmoji("et") },
  { name: "Falkland Islands", code: "fk", dialCode: "+500", flag: getFlagEmoji("fk") },
  { name: "Faroe Islands", code: "fo", dialCode: "+298", flag: getFlagEmoji("fo") },
  { name: "Fiji", code: "fj", dialCode: "+679", flag: getFlagEmoji("fj") },
  { name: "Finland", code: "fi", dialCode: "+358", flag: getFlagEmoji("fi") },
  { name: "France", code: "fr", dialCode: "+33", flag: getFlagEmoji("fr") },
  { name: "French Polynesia", code: "pf", dialCode: "+689", flag: getFlagEmoji("pf") },
  { name: "Gabon", code: "ga", dialCode: "+241", flag: getFlagEmoji("ga") },
  { name: "Gambia", code: "gm", dialCode: "+220", flag: getFlagEmoji("gm") },
  { name: "Georgia", code: "ge", dialCode: "+995", flag: getFlagEmoji("ge") },
  { name: "Germany", code: "de", dialCode: "+49", flag: getFlagEmoji("de") },
  { name: "Ghana", code: "gh", dialCode: "+233", flag: getFlagEmoji("gh") },
  { name: "Gibraltar", code: "gi", dialCode: "+350", flag: getFlagEmoji("gi") },
  { name: "Greece", code: "gr", dialCode: "+30", flag: getFlagEmoji("gr") },
  { name: "Greenland", code: "gl", dialCode: "+299", flag: getFlagEmoji("gl") },
  { name: "Grenada", code: "gd", dialCode: "+1473", flag: getFlagEmoji("gd") },
  { name: "Guam", code: "gu", dialCode: "+1671", flag: getFlagEmoji("gu") },
  { name: "Guatemala", code: "gt", dialCode: "+502", flag: getFlagEmoji("gt") },
  { name: "Guernsey", code: "gg", dialCode: "+44", flag: getFlagEmoji("gg") },
  { name: "Guinea", code: "gn", dialCode: "+224", flag: getFlagEmoji("gn") },
  { name: "Guinea-Bissau", code: "gw", dialCode: "+245", flag: getFlagEmoji("gw") },
  { name: "Guyana", code: "gy", dialCode: "+592", flag: getFlagEmoji("gy") },
  { name: "Haiti", code: "ht", dialCode: "+509", flag: getFlagEmoji("ht") },
  { name: "Honduras", code: "hn", dialCode: "+504", flag: getFlagEmoji("hn") },
  { name: "Hong Kong", code: "hk", dialCode: "+852", flag: getFlagEmoji("hk") },
  { name: "Hungary", code: "hu", dialCode: "+36", flag: getFlagEmoji("hu") },
  { name: "Iceland", code: "is", dialCode: "+354", flag: getFlagEmoji("is") },
  { name: "India", code: "in", dialCode: "+91", flag: getFlagEmoji("in") },
  { name: "Indonesia", code: "id", dialCode: "+62", flag: getFlagEmoji("id") },
  { name: "Iran", code: "ir", dialCode: "+98", flag: getFlagEmoji("ir") },
  { name: "Iraq", code: "iq", dialCode: "+964", flag: getFlagEmoji("iq") },
  { name: "Ireland", code: "ie", dialCode: "+353", flag: getFlagEmoji("ie") },
  { name: "Isle of Man", code: "im", dialCode: "+44", flag: getFlagEmoji("im") },
  { name: "Israel", code: "il", dialCode: "+972", flag: getFlagEmoji("il") },
  { name: "Italy", code: "it", dialCode: "+39", flag: getFlagEmoji("it") },
  { name: "Ivory Coast", code: "ci", dialCode: "+225", flag: getFlagEmoji("ci") },
  { name: "Jamaica", code: "jm", dialCode: "+1876", flag: getFlagEmoji("jm") },
  { name: "Japan", code: "jp", dialCode: "+81", flag: getFlagEmoji("jp") },
  { name: "Jersey", code: "je", dialCode: "+44", flag: getFlagEmoji("je") },
  { name: "Jordan", code: "jo", dialCode: "+962", flag: getFlagEmoji("jo") },
  { name: "Kazakhstan", code: "kz", dialCode: "+7", flag: getFlagEmoji("kz") },
  { name: "Kenya", code: "ke", dialCode: "+254", flag: getFlagEmoji("ke") },
  { name: "Kiribati", code: "ki", dialCode: "+686", flag: getFlagEmoji("ki") },
  { name: "Kosovo", code: "xk", dialCode: "+383", flag: getFlagEmoji("xk") },
  { name: "Kuwait", code: "kw", dialCode: "+965", flag: getFlagEmoji("kw") },
  { name: "Kyrgyzstan", code: "kg", dialCode: "+996", flag: getFlagEmoji("kg") },
  { name: "Laos", code: "la", dialCode: "+856", flag: getFlagEmoji("la") },
  { name: "Latvia", code: "lv", dialCode: "+371", flag: getFlagEmoji("lv") },
  { name: "Lebanon", code: "lb", dialCode: "+961", flag: getFlagEmoji("lb") },
  { name: "Lesotho", code: "ls", dialCode: "+266", flag: getFlagEmoji("ls") },
  { name: "Liberia", code: "lr", dialCode: "+231", flag: getFlagEmoji("lr") },
  { name: "Libya", code: "ly", dialCode: "+218", flag: getFlagEmoji("ly") },
  { name: "Liechtenstein", code: "li", dialCode: "+423", flag: getFlagEmoji("li") },
  { name: "Lithuania", code: "lt", dialCode: "+370", flag: getFlagEmoji("lt") },
  { name: "Luxembourg", code: "lu", dialCode: "+352", flag: getFlagEmoji("lu") },
  { name: "Macau", code: "mo", dialCode: "+853", flag: getFlagEmoji("mo") },
  { name: "Macedonia", code: "mk", dialCode: "+389", flag: getFlagEmoji("mk") },
  { name: "Madagascar", code: "mg", dialCode: "+261", flag: getFlagEmoji("mg") },
  { name: "Malawi", code: "mw", dialCode: "+265", flag: getFlagEmoji("mw") },
  { name: "Malaysia", code: "my", dialCode: "+60", flag: getFlagEmoji("my") },
  { name: "Maldives", code: "mv", dialCode: "+960", flag: getFlagEmoji("mv") },
  { name: "Mali", code: "ml", dialCode: "+223", flag: getFlagEmoji("ml") },
  { name: "Malta", code: "mt", dialCode: "+356", flag: getFlagEmoji("mt") },
  { name: "Marshall Islands", code: "mh", dialCode: "+692", flag: getFlagEmoji("mh") },
  { name: "Mauritania", code: "mr", dialCode: "+222", flag: getFlagEmoji("mr") },
  { name: "Mauritius", code: "mu", dialCode: "+230", flag: getFlagEmoji("mu") },
  { name: "Mayotte", code: "yt", dialCode: "+262", flag: getFlagEmoji("yt") },
  { name: "Mexico", code: "mx", dialCode: "+52", flag: getFlagEmoji("mx") },
  { name: "Micronesia", code: "fm", dialCode: "+691", flag: getFlagEmoji("fm") },
  { name: "Moldova", code: "md", dialCode: "+373", flag: getFlagEmoji("md") },
  { name: "Monaco", code: "mc", dialCode: "+377", flag: getFlagEmoji("mc") },
  { name: "Mongolia", code: "mn", dialCode: "+976", flag: getFlagEmoji("mn") },
  { name: "Montenegro", code: "me", dialCode: "+382", flag: getFlagEmoji("me") },
  { name: "Montserrat", code: "ms", dialCode: "+1664", flag: getFlagEmoji("ms") },
  { name: "Morocco", code: "ma", dialCode: "+212", flag: getFlagEmoji("ma") },
  { name: "Mozambique", code: "mz", dialCode: "+258", flag: getFlagEmoji("mz") },
  { name: "Myanmar", code: "mm", dialCode: "+95", flag: getFlagEmoji("mm") },
  { name: "Namibia", code: "na", dialCode: "+264", flag: getFlagEmoji("na") },
  { name: "Nauru", code: "nr", dialCode: "+674", flag: getFlagEmoji("nr") },
  { name: "Nepal", code: "np", dialCode: "+977", flag: getFlagEmoji("np") },
  { name: "Netherlands", code: "nl", dialCode: "+31", flag: getFlagEmoji("nl") },
  { name: "Netherlands Antilles", code: "an", dialCode: "+599", flag: getFlagEmoji("an") },
  { name: "New Caledonia", code: "nc", dialCode: "+687", flag: getFlagEmoji("nc") },
  { name: "New Zealand", code: "nz", dialCode: "+64", flag: getFlagEmoji("nz") },
  { name: "Nicaragua", code: "ni", dialCode: "+505", flag: getFlagEmoji("ni") },
  { name: "Niger", code: "ne", dialCode: "+227", flag: getFlagEmoji("ne") },
  { name: "Nigeria", code: "ng", dialCode: "+234", flag: getFlagEmoji("ng") },
  { name: "Niue", code: "nu", dialCode: "+683", flag: getFlagEmoji("nu") },
  { name: "North Korea", code: "kp", dialCode: "+850", flag: getFlagEmoji("kp") },
  { name: "Northern Mariana Islands", code: "mp", dialCode: "+1670", flag: getFlagEmoji("mp") },
  { name: "Norway", code: "no", dialCode: "+47", flag: getFlagEmoji("no") },
  { name: "Oman", code: "om", dialCode: "+968", flag: getFlagEmoji("om") },
  { name: "Pakistan", code: "pk", dialCode: "+92", flag: getFlagEmoji("pk") },
  { name: "Palau", code: "pw", dialCode: "+680", flag: getFlagEmoji("pw") },
  { name: "Palestine", code: "ps", dialCode: "+970", flag: getFlagEmoji("ps") },
  { name: "Panama", code: "pa", dialCode: "+507", flag: getFlagEmoji("pa") },
  { name: "Papua New Guinea", code: "pg", dialCode: "+675", flag: getFlagEmoji("pg") },
  { name: "Paraguay", code: "py", dialCode: "+595", flag: getFlagEmoji("py") },
  { name: "Peru", code: "pe", dialCode: "+51", flag: getFlagEmoji("pe") },
  { name: "Philippines", code: "ph", dialCode: "+63", flag: getFlagEmoji("ph") },
  { name: "Pitcairn", code: "pn", dialCode: "+64", flag: getFlagEmoji("pn") },
  { name: "Poland", code: "pl", dialCode: "+48", flag: getFlagEmoji("pl") },
  { name: "Portugal", code: "pt", dialCode: "+351", flag: getFlagEmoji("pt") },
  { name: "Puerto Rico", code: "pr", dialCode: "+1787", flag: getFlagEmoji("pr") },
  { name: "Qatar", code: "qa", dialCode: "+974", flag: getFlagEmoji("qa") },
  { name: "Republic of the Congo", code: "cg", dialCode: "+242", flag: getFlagEmoji("cg") },
  { name: "Reunion", code: "re", dialCode: "+262", flag: getFlagEmoji("re") },
  { name: "Romania", code: "ro", dialCode: "+40", flag: getFlagEmoji("ro") },
  { name: "Russia", code: "ru", dialCode: "+7", flag: getFlagEmoji("ru") },
  { name: "Rwanda", code: "rw", dialCode: "+250", flag: getFlagEmoji("rw") },
  { name: "Saint Barthelemy", code: "bl", dialCode: "+590", flag: getFlagEmoji("bl") },
  { name: "Saint Helena", code: "sh", dialCode: "+290", flag: getFlagEmoji("sh") },
  { name: "Saint Kitts and Nevis", code: "kn", dialCode: "+1869", flag: getFlagEmoji("kn") },
  { name: "Saint Lucia", code: "lc", dialCode: "+1758", flag: getFlagEmoji("lc") },
  { name: "Saint Martin", code: "mf", dialCode: "+590", flag: getFlagEmoji("mf") },
  { name: "Saint Pierre and Miquelon", code: "pm", dialCode: "+508", flag: getFlagEmoji("pm") },
  { name: "Saint Vincent and the Grenadines", code: "vc", dialCode: "+1784", flag: getFlagEmoji("vc") },
  { name: "Samoa", code: "ws", dialCode: "+685", flag: getFlagEmoji("ws") },
  { name: "San Marino", code: "sm", dialCode: "+378", flag: getFlagEmoji("sm") },
  { name: "Sao Tome and Principe", code: "st", dialCode: "+239", flag: getFlagEmoji("st") },
  { name: "Saudi Arabia", code: "sa", dialCode: "+966", flag: getFlagEmoji("sa") },
  { name: "Senegal", code: "sn", dialCode: "+221", flag: getFlagEmoji("sn") },
  { name: "Serbia", code: "rs", dialCode: "+381", flag: getFlagEmoji("rs") },
  { name: "Seychelles", code: "sc", dialCode: "+248", flag: getFlagEmoji("sc") },
  { name: "Sierra Leone", code: "sl", dialCode: "+232", flag: getFlagEmoji("sl") },
  { name: "Singapore", code: "sg", dialCode: "+65", flag: getFlagEmoji("sg") },
  { name: "Sint Maarten", code: "sx", dialCode: "+1721", flag: getFlagEmoji("sx") },
  { name: "Slovakia", code: "sk", dialCode: "+421", flag: getFlagEmoji("sk") },
  { name: "Slovenia", code: "si", dialCode: "+386", flag: getFlagEmoji("si") },
  { name: "Solomon Islands", code: "sb", dialCode: "+677", flag: getFlagEmoji("sb") },
  { name: "Somalia", code: "so", dialCode: "+252", flag: getFlagEmoji("so") },
  { name: "South Africa", code: "za", dialCode: "+27", flag: getFlagEmoji("za") },
  { name: "South Korea", code: "kr", dialCode: "+82", flag: getFlagEmoji("kr") },
  { name: "South Sudan", code: "ss", dialCode: "+211", flag: getFlagEmoji("ss") },
  { name: "Spain", code: "es", dialCode: "+34", flag: getFlagEmoji("es") },
  { name: "Sri Lanka", code: "lk", dialCode: "+94", flag: getFlagEmoji("lk") },
  { name: "Sudan", code: "sd", dialCode: "+249", flag: getFlagEmoji("sd") },
  { name: "Suriname", code: "sr", dialCode: "+597", flag: getFlagEmoji("sr") },
  { name: "Svalbard and Jan Mayen", code: "sj", dialCode: "+47", flag: getFlagEmoji("sj") },
  { name: "Swaziland", code: "sz", dialCode: "+268", flag: getFlagEmoji("sz") },
  { name: "Sweden", code: "se", dialCode: "+46", flag: getFlagEmoji("se") },
  { name: "Switzerland", code: "ch", dialCode: "+41", flag: getFlagEmoji("ch") },
  { name: "Syria", code: "sy", dialCode: "+963", flag: getFlagEmoji("sy") },
  { name: "Taiwan", code: "tw", dialCode: "+886", flag: getFlagEmoji("tw") },
  { name: "Tajikistan", code: "tj", dialCode: "+992", flag: getFlagEmoji("tj") },
  { name: "Tanzania", code: "tz", dialCode: "+255", flag: getFlagEmoji("tz") },
  { name: "Thailand", code: "th", dialCode: "+66", flag: getFlagEmoji("th") },
  { name: "Togo", code: "tg", dialCode: "+228", flag: getFlagEmoji("tg") },
  { name: "Tokelau", code: "tk", dialCode: "+690", flag: getFlagEmoji("tk") },
  { name: "Tonga", code: "to", dialCode: "+676", flag: getFlagEmoji("to") },
  { name: "Trinidad and Tobago", code: "tt", dialCode: "+1868", flag: getFlagEmoji("tt") },
  { name: "Tunisia", code: "tn", dialCode: "+216", flag: getFlagEmoji("tn") },
  { name: "Turkey", code: "tr", dialCode: "+90", flag: getFlagEmoji("tr") },
  { name: "Turkmenistan", code: "tm", dialCode: "+993", flag: getFlagEmoji("tm") },
  { name: "Turks and Caicos Islands", code: "tc", dialCode: "+1649", flag: getFlagEmoji("tc") },
  { name: "Tuvalu", code: "tv", dialCode: "+688", flag: getFlagEmoji("tv") },
  { name: "U.S. Virgin Islands", code: "vi", dialCode: "+1340", flag: getFlagEmoji("vi") },
  { name: "Uganda", code: "ug", dialCode: "+256", flag: getFlagEmoji("ug") },
  { name: "Ukraine", code: "ua", dialCode: "+380", flag: getFlagEmoji("ua") },
  { name: "United Arab Emirates", code: "ae", dialCode: "+971", flag: getFlagEmoji("ae") },
  { name: "United Kingdom", code: "gb", dialCode: "+44", flag: getFlagEmoji("gb") },
  { name: "United States", code: "us", dialCode: "+1", flag: getFlagEmoji("us") },
  { name: "Uruguay", code: "uy", dialCode: "+598", flag: getFlagEmoji("uy") },
  { name: "Uzbekistan", code: "uz", dialCode: "+998", flag: getFlagEmoji("uz") },
  { name: "Vanuatu", code: "vu", dialCode: "+678", flag: getFlagEmoji("vu") },
  { name: "Vatican", code: "va", dialCode: "+379", flag: getFlagEmoji("va") },
  { name: "Venezuela", code: "ve", dialCode: "+58", flag: getFlagEmoji("ve") },
  { name: "Vietnam", code: "vn", dialCode: "+84", flag: getFlagEmoji("vn") },
  { name: "Wallis and Futuna", code: "wf", dialCode: "+681", flag: getFlagEmoji("wf") },
  { name: "Western Sahara", code: "eh", dialCode: "+212", flag: getFlagEmoji("eh") },
  { name: "Yemen", code: "ye", dialCode: "+967", flag: getFlagEmoji("ye") },
  { name: "Zambia", code: "zm", dialCode: "+260", flag: getFlagEmoji("zm") },
  { name: "Zimbabwe", code: "zw", dialCode: "+263", flag: getFlagEmoji("zw") }
];
