export const countries = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
  "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica",
  "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon",
  "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Heard Island and McDonald Islands", "Holy See", "Honduras", "Hong Kong SAR China", "Hungary", "Iceland", "India", "Indonesia", "Iran",
  "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
  "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho",
  "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Madagascar", "Malawi", "Malaysia", "Maldives",
  "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
  "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua",
  "Niger", "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea",
  "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
  "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
  "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan",
  "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo",
  "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
  "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const timezones = [
  { name: "Pacific/Midway", label: "Midway Island, American Samoa Time", offset: "-11:00" },
  { name: "Pacific/Honolulu", label: "Hawaii Standard Time", offset: "-10:00" },
  { name: "America/Anchorage", label: "Alaska Standard Time", offset: "-09:00" },
  { name: "America/Los_Angeles", label: "Pacific Time", offset: "-08:00" },
  { name: "America/Denver", label: "Mountain Time", offset: "-07:00" },
  { name: "America/Chicago", label: "Central Time", offset: "-06:00" },
  { name: "America/New_York", label: "Eastern Time", offset: "-05:00" },
  { name: "America/Caracas", label: "Venezuela Time", offset: "-04:30" },
  { name: "America/Halifax", label: "Atlantic Time", offset: "-04:00" },
  { name: "America/St_Johns", label: "Newfoundland Time", offset: "-03:30" },
  { name: "America/Sao_Paulo", label: "Brasilia Time", offset: "-03:00" },
  { name: "Atlantic/South_Georgia", label: "Mid-Atlantic Time", offset: "-02:00" },
  { name: "Atlantic/Azores", label: "Azores Time", offset: "-01:00" },
  { name: "Europe/London", label: "Greenwich Mean Time", offset: "+00:00" },
  { name: "Europe/Paris", label: "Central European Time", offset: "+01:00" },
  { name: "Africa/Cairo", label: "Eastern European Time", offset: "+02:00" },
  { name: "Europe/Moscow", label: "Moscow Time", offset: "+03:00" },
  { name: "Asia/Dubai", label: "Gulf Standard Time", offset: "+04:00" },
  { name: "Asia/Kabul", label: "Afghanistan Time", offset: "+04:30" },
  { name: "Asia/Karachi", label: "Pakistan, Maldives Time", offset: "+05:00" },
  { name: "Asia/Kolkata", label: "India, Sri Lanka Time", offset: "+05:30" },
  { name: "Asia/Kathmandu", label: "Kathmandu Time", offset: "+05:45" },
  { name: "Asia/Dhaka", label: "Bangladesh Time", offset: "+06:00" },
  { name: "Asia/Rangoon", label: "Myanmar Time", offset: "+06:30" },
  { name: "Asia/Bangkok", label: "Indochina Time", offset: "+07:00" },
  { name: "Asia/Shanghai", label: "China Standard Time", offset: "+08:00" },
  { name: "Asia/Tokyo", label: "Japan Standard Time", offset: "+09:00" },
  { name: "Australia/Adelaide", label: "Australian Central Time", offset: "+09:30" },
  { name: "Australia/Sydney", label: "Australian Eastern Time", offset: "+10:00" },
  { name: "Pacific/Guadalcanal", label: "Solomon Islands Time", offset: "+11:00" },
  { name: "Pacific/Auckland", label: "New Zealand Standard Time", offset: "+12:00" },
  { name: "Asia/Omsk", label: "Asia/Omsk", offset: "+06:00" },
  { name: "Asia/Krasnoyarsk", label: "Krasnoyarsk Time", offset: "+07:00" },
];
